export * from "./Auth.service";
export * from "./StudySet.service";
export * from "./Term.service";
export * from "./Class.service";
export * from "./Test.service";
export * from "./User.service";
export * from "./StudySetReport.service";
export * from './Folder.service';
export * from './Permissions.service';